### ISSUE TITLE
Documentation incorrect about defining Kafka servers

### ISSUE THREAD

**Issue by dstepanov** [micronaut-projects/micronaut-kafka#193]
```
kafka:
    bootstrap:
        servers:
            - foo:9092
            - bar:9092
```

This will no work, it needs to be one string `servers: foo:9092,bar:9092`
