### ISSUE TITLE
Support the configuration of the schema registry url for Avro serializer/deserializer

### ISSUE THREAD

**Issue by codependent** [micronaut-projects/micronaut-kafka#32]
According to the documentation we can specify different serializers/deserializers for producers/consumers in the configuration, e.g:
```
kafka:
    producers:
        xxx:
            value:
                serializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
```

In order to use with Avro we would need to be able to configure the schema registry url.

**Comment by graemerocher** [comment]
You can configure anything you want in kafka below `xxx`. Micronaut does not prevent that.

**Comment by ckosmowski** [comment]
I think what was meant by the opener of this ticket is. If you use `io.confluent.kafka.serializers.KafkaAvroSerializer` as the serializer configured for the producers, this serializer needs an instance of the type `SchemaRegistryClient` in its constructor to function properly. And to create such an instance you will need an url.

However the problem here (to me) is that you are unable to tell micronaut how to instantiate the serializer.

**Comment by kalgecin** [comment]
```
kafka:
  bootstrap:
    servers: xxx:99092
  consumers:
    default:
      specific.avro.reader: true
      key.deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      schema.registry.url: http://registry-server-url:port
```
this works for me
