### ISSUE TITLE
Restrict AdminClient permission for KafkaHealthIndicator

### ISSUE THREAD

**Issue by xiabai84** [micronaut-projects/micronaut-kafka#423]
### Expected Behavior

By enabling kafka.health.check Micronaut should only get the essential information, which is used for making health check.

### Actual Behaviour

As request result from AdminClient the DescribeClusterResult also contains sensitive information like ACLs, which could lead to a security issue. This request should be restricted by default configuration.

### Steps To Reproduce

1. Set ACLs for client user and kafka topics.
2. Revoke DescribeCluster permission from client user.
3. Enable kafka.health.check 
4. Start applicaiton

### Environment Information

- MacOS
- JDK 11

### Version

3.0.0

**Comment by jonasgeiregat** [comment]
In a way I think this is in a way related to  #440 

I was thinking of introducing different health strategies through a property.

If your user does not have _DescribeClusterResult_ ACL how do your propose to do the health check ? Also what risks are there if the cluster ACLs are fetched upon receiving the DescribeClusterResult result ?

**Comment by xiabai84** [comment]
Hey @jonasgeiregat,
I follow the point of issue #440 . For me min.insync.replicas would be enough to send out an alert, if the topic can't reach the predefined number of replicas after certain time. 
_DescribeClusterResult_ requires admin permission in an enterprise / multi tenant kerberized kafka cluster. And cluster administrator normally don't want to assign such permission to each tenant, if they even don't know each other.

I think the proper way is to overwrite KafkaHealthIndicator, but as a easy workaround we just enabled common micronaut health endpoints: 
```
endpoints:
  health:
    details-visible: ANONYMOUS
    enabled: true
    sensitive: false
```
and set "kafka.streams.health.enabled" to "false" in application.yml:
```
kafka:
  ....
  streams:
      health:
        enabled: false
        streams:
          enabled: true
      default:
        auto.offset.reset: earliest
        processing.guarantee: exactly_once
        sasl.jaas.config: xxxxxxx
  ...
```

**Comment by jonasgeiregat** [comment]
I'm not sure giving a client the _DescribeClusterResult_ ACL would violate one of the GDPR rules. As no personal or identifiable information seems to be exposed by the __DescribeClusterResult__ ACL. But then again I'm not a GDPR expert.

In any case I would propose to have a set of HealthIndicators available, the current one still being the default by through configuration could be overridden. 

The following would enable a kafka HealthIndicator based upon the _min.insync.replicas_ cluster property.

This then would also solve #440

```
kafka:
  health:
    enabled: true
    strategy: insync_replicas
```
