### ISSUE TITLE
Breaking change between 4.0.0 -> 4.1.1 Consumer properties not loaded from application.yml file when using uniqueGroupId = true

### ISSUE THREAD

**Issue by StephanePaulus** [micronaut-projects/micronaut-kafka#519]
### Expected Behavior

When using having this KafkaListener in Micronaut Kafka 4.0.0
````
@KafkaListener(
    groupId = "groupid",
    uniqueGroupId = true,
    offsetReset = OffsetReset.EARLIEST)
public class Consumer 
````

I was able to set the consumer properties by setting this in the application.yaml file

````
consumers:
        groupid:
          key:
            deserializer: proto.kafka.serdes.StringValueSerde
          value:
            deserializer: proto.kafka.serdes.NotificationSerde
          fetch.min.bytes: 20971520
          fetch.max.bytes: 52428800
````

I still expected this to work after upgrading micronaut-kafka

### Actual Behaviour

When using described configuration, the default consumer settings will be used in 4.1.1. Making my code fail as I need custom deserializers.

### Steps To Reproduce

1. Create a kafka listener with a groupId  and uniqueGroupId = true
2. Set some non default values in application.yaml file under the kafka.consumers.{groupID} property
3. Check the values on the consumer that gets created. You will not found your values.

### Version

3.3.3
