### ISSUE TITLE
Document how to activate specific.avro.reader in configuration

### ISSUE THREAD

**Issue by paulolieuthier** [micronaut-projects/micronaut-kafka#55]
I got it working through the annotations:

```
@KafkaListener(groupId = "group-name",
        properties = @Property(name = KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, value = "true"))
public class ExampleKafkaConsumer {
```

But I would like to set it in the configuration file.

**Comment by graemerocher** [comment]
Configuring consumers is covered here:

https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaListenerConfiguration

You should be able to specify the value of `SPECIFIC_AVRO_READER_CONFIG` as a configuration property.

**Comment by paulolieuthier** [comment]
Indeed. That was enough:

```
kafka:
  consumers:
    default:
      specific:
        avro:
          reader: true
```
