### ISSUE TITLE
Auto-create topic with N partitions

### ISSUE THREAD

**Issue by ivangfr** [micronaut-projects/micronaut-kafka#66]
Hey guys!

I have implemented a simple producer-consumer application using Micronaut-Kafka (here is the link:  https://github.com/ivangfr/graalvm-quarkus-micronaut-springboot/tree/master/producer-consumer/micronaut-producer-consumer). Everytime I run it, if the topic they use doesn't exist, it is created with just one partition.

I would like to know if there is any property on the Kafka configuration (producer or consumer side) where I can set the number of partitions a topic must have.

Best regards

**Comment by jgray1206** [comment]
I believe auto-create uses the cluster's `num.partitions` config setting. Which defaults to one. If you want auto-create to default create a topic with N partitions, just set that config on the cluster to N. You can use `default.replication.factor` to set the auto-created topic's replication factor, too.

**Comment by ivangfr** [comment]
Hey @jgray1206 thanks for the response.

I've found this ticker https://github.com/micronaut-projects/micronaut-kafka/issues/41
Here, he is using the `embedded` kafka
```
kafka:
  embedded:
    enabled: true
    topics: my-topic
    properties:
      num.partitions: 10
```

I am not using `embedded`... So, I tried like that
```
kafka:
  bootstrap:
    servers: localhost:9092
  producers:
    properties:
      num.partitions: 5
```
However, it didn't work. Any idea?
